### ISSUE TITLE
Naming suggestion

### ISSUE THREAD

**Issue by henryruhs** [jahed/grunt-json-format#2]
Hello,

thank you for the great plugin... I'd like to suggest that you rename the task configuration from 'json-format' to jsonFormat or the whole plugin to format-json and formatJSON ...

**Comment by jahed** [comment]
Any reason as to why? I haven't used Grunt recently but I thought the naming convention for most plugins was kebab-cased.

If this is mainly a one-off thing or to avoid quoted object keys, consider using `grunt.renameTask`. More info here: http://gruntjs.com/api/grunt.task#grunt.task.renametask

**Comment by henryruhs** [comment]
Reason why? Hmm, I think Javascript is a camelCase language!? Thank you for the suggestion. I will use the rename task feature.

**Comment by jahed** [comment]
While I agree JS should use camelCase where ever possible, in this case, there's already a convention to use kebab-case for Grunt plugins and going against that would cause more confusion.
